-- Run this in your Supabase SQL Editor

CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  
  -- Personal Info
  name TEXT NOT NULL,
  nim TEXT NOT NULL,
  email TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  prodi TEXT NOT NULL, -- Program Studi
  
  -- Choices
  dept1 TEXT NOT NULL,
  div1 TEXT NOT NULL,
  reason1 TEXT,
  dept2 TEXT,
  div2 TEXT,
  reason2 TEXT,
  
  -- Essays / Details
  org_experience TEXT, -- Pengalaman Organisasi
  skills TEXT,         -- Skill / Keahlian
  commitment TEXT,     -- Komitmen Pelayanan
  main_reason TEXT,    -- Alasan ingin melayani
  
  -- Status / Booleans
  active_period BOOLEAN DEFAULT false, -- Bersedia aktif 1 periode
  willing_transfer BOOLEAN DEFAULT false,
  
  -- Files
  sertif_url TEXT,     -- Sertifikat / Pengalaman
  portfolio_url TEXT   -- Portofolio
);

-- Initial Storage setup is done via Dashboard (Create bucket 'uploads' -> Public)
